# Generated by Django 6.0.3 on 2026-04-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_ai_answer_ticket_is_helpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
