# Generated by Django 6.0.3 on 2026-04-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticket_is_auto_resolved_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Raised', 'Raised'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Solved', 'Solved')], default='New', max_length=50),
        ),
    ]
