# Generated by Django 6.0.3 on 2026-04-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('estimated_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
