# Generated by Django 6.0.3 on 2026-04-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reason',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
