# Generated by Django 6.0.3 on 2026-04-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Raised', 'Raised'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Solved', 'Solved')], default='New', max_length=50),
        ),
    ]
