# Generated by Django 6.0.3 on 2026-04-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_notes_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
    ]
