# Generated by Django 6.0.3 on 2026-04-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_employee_actionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='ActionLog',
        ),
    ]
