# Generated by Django 6.0.3 on 2026-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_auto_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
